# Generated by Django 5.2 on 2025-05-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taikhoan',
            options={'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Tài khoản'},
        ),
        migrations.AlterModelManagers(
            name='taikhoan',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='taikhoan',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='taikhoan',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='taikhoan',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='taikhoan',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='dia_chi',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Email đã được sử dụng.'}, max_length=255, null=True, unique=True, verbose_name='Địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Truy cập quản trị'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='loai_tk',
            field=models.CharField(choices=[('khach_hang', 'Khách hàng'), ('nhan_vien', 'Nhân viên'), ('admin', 'Quản lý')], default='khach_hang', max_length=20, verbose_name='Loại tài khoản'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='sdt',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='username',
            field=models.CharField(error_messages={'unique': 'Tên đăng nhập đã tồn tại.'}, max_length=150, unique=True, verbose_name='Tên đăng nhập'),
        ),
    ]
